export const projects = [
  {
    id: 'aimagic',
    title: 'AIMagic',
    subtitle: '独立全栈 · 从零到上线。',
    category: '独立全栈 · 已上线',
    stack: ['Vue 3', 'TypeScript', 'Node.js', 'Docker', 'Nginx'],
    description: '独立完成 AI 创意工具平台的全部工作——产品设计、前后端开发、服务器运维与部署上线，并自主完成推广投放与商业化运营。',
    highlights: [
      '独立搭建前后端架构，集成百炼图像与万相视频能力，提供风格转换、照片修复、照片微动等创意工具。',
      '独立实现短信登录、JWT 鉴权、支付宝与微信支付，打通积分和会员体系。',
      '独立构建生成任务队列、会员优先处理、作品历史及失败积分返还。',
      '独立完成 Docker / Nginx 部署与运维，支持健康检查、版本发布与失败回滚。',
    ],
    website: 'https://aimagic.wdsite.cn/',
    image: '/assets/aimagic-preview.webp',
  },
  {
    id: 'canvas',
    title: 'AI 无限画布',
    subtitle: '把灵感，连接成创作流程。',
    category: '开源二次开发 · AI 创作',
    stack: ['React', 'TypeScript', 'Zustand', 'Canvas'],
    description: '基于开源 infinite-canvas 扩展图片与视频创作，在节点、连线与素材体系上接入多模型、提示词优化及连续视频生成。',
    highlights: [
      '适配百炼文本、图片及视频接口，处理首尾帧、多参考图、异步任务与轮询。',
      '通过 HTMLVideoElement 与 Canvas 提取视频末帧，衔接下一段视频生成。',
      '自动创建参考图片节点并连接视频节点，继承模型与比例配置。',
      '在节点提示词面板接入 AI 优化，覆盖不同创作类型与异常反馈。',
    ],
  },
  {
    id: 'energy',
    title: '光储充智慧微电网',
    subtitle: '让能源数据，在三维空间中可见。',
    category: '企业项目 · 三维可视化',
    stack: ['Blender', 'Three.js', 'Vue 3', 'G6 / ECharts'],
    description: '富仁高科光储充示范项目大屏，以三维场景呈现光伏、储能、充电桩、市电与负荷的连接关系，结合电量统计、收益分析、实时功率与告警展示全站运行状态。围绕 Blender 模型与 Three.js，完成设备交互和业务数据联动。',
    website: 'https://dev.furenenergy.com/demo/smart-net-prod/#/index',
    websiteLabel: '打开微电网大屏 ↗',
    preview: { src: './assets/microgrid-dashboard-preview.webp', full: './assets/microgrid-dashboard-full.webp', alt: '富仁高科光储充示范项目全站概览大屏', caption: '全站概览 · 项目实际运行界面，在线大屏建议横屏浏览' },
    highlights: [
      '加载 GLB / glTF 设备资源，通过射线拾取、组件分解与动画呈现设备结构。',
      '联动电池状态、温度等信息，接入 Draco / KTX2 资源压缩。',
      '实现 AI 流式问答、设备上下文、语音输入与告警联动。',
      '结合站点拓扑与运营图表，支持中英德日多语言及德国项目交付。',
    ],
  },
  {
    id: 'studio',
    title: 'Beta 运营与短视频工厂',
    subtitle: '把内容生产，交给可视化工具。',
    category: '企业项目 · 内容生产工具',
    stack: ['H5 编辑器', 'Lottie', 'RecordRTC', '多端渲染'],
    description: '打造可视化 H5 编辑与短视频制作工具，让运营内容从元素编排走向移动端页面和动画视频。',
    highlights: [
      '实现可视化 H5 编辑，将元素位置与属性序列化并在移动端渲染。',
      '构建短视频编辑工具，支持图层编排与 Lottie 素材预览。',
      '使用 RecordRTC 完成动画录制，衔接内容编辑与视频产出。',
    ],
  },
];
